### ISSUE TITLE
Example not loading...

### ISSUE THREAD

**Issue by aztlan2k** [ajanes93/vuetify-snackbar-queue#2]
Hey, I noticed your project for `vuetify-snackbar-queue` and just wanted to let you know that the link you currently have for the example on CodeSandbox does not actually load this as an example.

https://codesandbox.io/s/z2v919669m

When you go to that sandbox the `App.vue` you load doesn't even display a snackbar.  You may want to update your example on CodeSandbox.

Also, even after manually taking your example code from your README and applying it to that sandbox (straight copy-n-paste)... it works on bringing up the first snackbar but then the snackbar timesout and never comes up again.

**Comment by ajanes93** [comment]
Hi,  thanks for letting me know.  This has now been fixed.  This component wasn't being actively maintained.  Sorry for the inconvenience.  https://codesandbox.io/s/z2v919669m
