### ISSUE TITLE
Prop for the Next count

### ISSUE THREAD

**Issue by plundermun** [ajanes93/vuetify-snackbar-queue#20]
Hi, first of all thank you for the nice plugin.
I'm using it in a non english project, so I stumpled over the static word "more" for the queued item count, it would maybe nice to have a prop for this word too.

**Comment by ajanes93** [comment]
Hi

I've added a prop for this called "nextButtonCountText", see [Commit f43767d](https://github.com/ajanes93/vuetify-snackbar-queue/pull/22/commits/f43767dd0e00a4cd9c98b437f33b9e0ff453f155).  The documentation has also been updated.  This is available from version 2.3.0.
