### ISSUE TITLE
Queue system fails if Timeout is set

### ISSUE THREAD

**Issue by bhaskar-nair2** [ajanes93/vuetify-snackbar-queue#3]
The queue system will fail if the timeout is set on the component. as all the occurrences disappear at the given timeout.

**Comment by ajanes93** [comment]
Hi, thanks for opening this issue.  Are you able to provide a reproduction of the bug you are describing?  Maybe by forking [this code sandbox](https://codesandbox.io/s/z2v919669m) .  I can't seem to be able to replicate the issue you are describing.  Thanks.

**Comment by bhaskar-nair2** [comment]
I legit opened this an year ago..

**Comment by ajanes93** [comment]
This wasn't being actively maintained, it was just a quick thing I needed at the time.  This will be more actively maintained going forwards.  Sorry for the inconvenience.
