### ISSUE TITLE
avoid using underscore

### ISSUE THREAD

**Issue by MathieuDerelle** [ajanes93/vuetify-snackbar-queue#4]
I'd like to use this component, but you are using `underscore`
(and im using `lodash-es`)

`import {first, isEmpty} from 'underscore'`

it seems a high cost for those 2 fews things

1.

https://github.com/ajanes93/vuetify-snackbar-queue/blob/5c2272e3408736455cda31f77cd189914853a8cb/src/components/VSnackbarQueue.vue#L108
replaced by `vm.items.length > 0`

(you did it some lines below)

https://github.com/ajanes93/vuetify-snackbar-queue/blob/5c2272e3408736455cda31f77cd189914853a8cb/src/components/VSnackbarQueue.vue#L122

2.

https://github.com/ajanes93/vuetify-snackbar-queue/blob/5c2272e3408736455cda31f77cd189914853a8cb/src/components/VSnackbarQueue.vue#L109
replaced by `vm.items[0]`

**Comment by ajanes93** [comment]
Hi, thanks for opening this issue.  I agree there was no need to use underscore, and at the time it was just a quick component I needed, so I didn't really think about it.  This component wasn't being actively maintained but it will be going forwards.  Please see [Commit 6efff985](https://github.com/ajanes93/vuetify-snackbar-queue/pull/5/commits/6efff985f043e4c30aee7197c697560288e18457) which removes the use of underscore.  This has also been published as [version 0.1.0](https://www.npmjs.com/package/vuetify-snackbar-queue) on npm
